import type { HadsQuestion } from "../types/hads";

export const hadsQuestions: HadsQuestion[] = [
  {
    id: "q1",
    number: 1,
    text: "Я чувствую себя напряженно или «на взводе»",
    domain: "anxiety",
    options: [
      { value: 3, label: "Все время" },
      { value: 2, label: "Часто" },
      { value: 1, label: "Время от времени" },
      { value: 0, label: "Совсем не испытываю" },
    ],
  },
  {
    id: "q2",
    number: 2,
    text: "Мне по-прежнему приносит удовольствие то, что приносило его раньше",
    domain: "depression",
    options: [
      { value: 0, label: "Определенно, это так" },
      { value: 1, label: "В меньшей степени, чем раньше" },
      { value: 2, label: "Совсем немного" },
      { value: 3, label: "Практически не приносит удовольствия" },
    ],
  },
  {
    id: "q3",
    number: 3,
    text: "У меня возникает чувство, как будто я напуган(а), как будто что-то ужасное сейчас происходит",
    domain: "anxiety",
    options: [
      { value: 3, label: "Определенно, это так, и страх очень сильный" },
      { value: 2, label: "Да, это так, но страх не очень сильный" },
      { value: 1, label: "Немного, но это меня не беспокоит" },
      { value: 0, label: "Совсем не испытываю" },
    ],
  },
  {
    id: "q4",
    number: 4,
    text: "Я могу смеяться и видеть смешную сторону вещей",
    domain: "depression",
    options: [
      { value: 0, label: "В той же степени, как это обычно для меня" },
      { value: 1, label: "Несколько в меньшей степени, чем обычно" },
      { value: 2, label: "В значительно меньшей степени, чем обычно" },
      { value: 3, label: "Совершенно не способен(на)" },
    ],
  },
  {
    id: "q5",
    number: 5,
    text: "Тревожные мысли приходят мне на ум",
    domain: "anxiety",
    options: [
      { value: 3, label: "Большую часть времени" },
      { value: 2, label: "Значительную часть времени" },
      { value: 1, label: "Время от времени, но не слишком часто" },
      { value: 0, label: "Только иногда" },
    ],
  },
  {
    id: "q6",
    number: 6,
    text: "Я жизнерадостный(ная)",
    domain: "depression",
    options: [
      { value: 3, label: "Совершенно нет" },
      { value: 2, label: "Редко" },
      { value: 1, label: "Периодически" },
      { value: 0, label: "Большую часть времени" },
    ],
  },
  {
    id: "q7",
    number: 7,
    text: "Я легко могу сесть и расслабиться",
    domain: "anxiety",
    options: [
      { value: 0, label: "Определенно, это так" },
      { value: 1, label: "Обычно это так" },
      { value: 2, label: "Изредка" },
      { value: 3, label: "Совсем не могу" },
    ],
  },
  {
    id: "q8",
    number: 8,
    text: "Я чувствую себя как будто замедленным(ой)",
    domain: "depression",
    options: [
      { value: 3, label: "Практически все время" },
      { value: 2, label: "Часто" },
      { value: 1, label: "Иногда" },
      { value: 0, label: "Совсем нет" },
    ],
  },
  {
    id: "q9",
    number: 9,
    text: "Я чувствую, как будто напуган(а) так, что все внутри холодеет",
    domain: "anxiety",
    options: [
      { value: 0, label: "Совсем не испытываю" },
      { value: 1, label: "Иногда" },
      { value: 2, label: "Часто" },
      { value: 3, label: "Очень часто" },
    ],
  },
  {
    id: "q10",
    number: 10,
    text: "Я не слежу за своей внешностью",
    domain: "depression",
    options: [
      { value: 3, label: "Определенно это так" },
      { value: 2, label: "Я не уделяю этому столько времени, сколько нужно" },
      { value: 1, label: "Возможно, я стал(а) меньше уделять этому внимания" },
      { value: 0, label: "Я слежу за собой так же, как и раньше" },
    ],
  },
  {
    id: "q11",
    number: 11,
    text: "Я испытываю беспокойство, как будто мне все время нужно двигаться",
    domain: "anxiety",
    options: [
      { value: 3, label: "В весьма выраженной степени" },
      { value: 2, label: "В значительной степени" },
      { value: 1, label: "В незначительной степени" },
      { value: 0, label: "Совсем не испытываю" },
    ],
  },
  {
    id: "q12",
    number: 12,
    text: "Я с удовольствием предвкушаю события",
    domain: "depression",
    options: [
      { value: 0, label: "Так же, как обычно" },
      { value: 1, label: "В меньшей степени, чем раньше" },
      { value: 2, label: "Значительно меньше, чем обычно" },
      { value: 3, label: "Практически нет" },
    ],
  },
  {
    id: "q13",
    number: 13,
    text: "Меня охватывает внезапная паника",
    domain: "anxiety",
    options: [
      { value: 3, label: "Очень часто" },
      { value: 2, label: "Довольно часто" },
      { value: 1, label: "Не так уж часто" },
      { value: 0, label: "Совсем не возникает" },
    ],
  },
  {
    id: "q14",
    number: 14,
    text: "Я могу получить удовольствие от хорошей книги, радио- или телепрограммы",
    domain: "depression",
    options: [
      { value: 0, label: "Часто" },
      { value: 1, label: "Иногда" },
      { value: 2, label: "Редко" },
      { value: 3, label: "Очень редко" },
    ],
  },
];
